### ISSUE TITLE
Categories list

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Reklambutiken#7]
In initial state - show a table with categories with parent 0 (root categories). Fetch like this: 
`GET http://api.reklambutiken.com/v1/categories/{id}/subcategories`

Draw a table like:

id | name | edit-button

When you click the name for a category, we should change route and show it's subcategories instead.

-----
**Components**
- add module 'categories' and base component. It should have lazy loading. 
- add route to this page and button to the left sidebar. `Categories` and subitem 'List'. List should be default page and use `0` as a base `id` for initial request. 
- add `Bordered Table` from Sing template with cols `ID | Name | `. Last col for edit button (pencil icon)(disabled for this task). Draw the table in a full width container.
- `Name` col should have click handler with routing to the same page but with incoming `id`. It's moving to subcategories.

**Services**
- add categories service in this module
- add method for fetching data of subcategories. id is 0 by default.
`GET http://api.reklambutiken.com/v1/categories/{id}/subcategories`

**Comment by user-one-myteam** [comment]
3-4 hours
