### ISSUE TITLE
Categories routes

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Reklambutiken#8]
A category can have multiple routes (url's). We should present a table where users can add routes.
To list all routes for a category:
To add a new category route:
POST http://api.reklambutiken.com/v1/routes/category/{id}
{ "slug": "foo/bar" }

This will make https://reklambutiken.com/foo/bar link to the specified category id. A user should be able to select which of the routes is the primary (all other will redirect to the primary). The primary route should be PUT:ed to the category resource:

PUT http://api.reklambutiken.com/v1/categories/{id}
{ "slug": "foo/bar" }

----
**Component**
- add component and route 'add routes'
- use bordered table for display incoming routes
- under the table should be button "Add Route" and form for `slug` and checkbox for `primary`

**Service**
- add method for getting category routes. Use id: 0 as default.
`GET http://api.reklambutiken.com/v1/routes/category/{id}`
- add method for adding new _category route_. 
Incoming data might have `{primary: true}`, it means we should use `PUT` request instead `POST`. `POST/PUT http://api.reklambutiken.com/v1/routes/category/{id}` with body `{ "slug": "foo/bar" }`

**Comment by user-one-myteam** [comment]
4-6 hours
